// This file is auto-generated by: bun run db:types
// Run `bun run db:types` from packages/supabase after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          cpf: string | null;
          birth_date: string | null;
          role: "customer" | "staff" | "admin";
          is_founding_member: boolean;
          founding_discount_used: boolean;
          credits_balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at"> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      pc_stations: {
        Row: {
          id: string;
          station_number: number;
          label: string | null;
          is_active: boolean;
          specs: Json | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["pc_stations"]["Row"], "created_at"> & {
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["pc_stations"]["Insert"]>;
      };
      sessions: {
        Row: {
          id: string;
          customer_id: string;
          station_id: string;
          package_type: "hora_vale" | "hora_pico" | "pacote_3h" | "corujao";
          started_at: string;
          ended_at: string | null;
          planned_end_at: string | null;
          status: "active" | "completed" | "cancelled";
          price_cents: number;
          transaction_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["sessions"]["Row"], "created_at"> & {
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["sessions"]["Insert"]>;
      };
      transactions: {
        Row: {
          id: string;
          customer_id: string;
          amount_cents: number;
          type: "purchase" | "refund" | "credit_add" | "credit_use";
          payment_method: "pix" | "credit_card" | "debit_card" | "credits" | "cash";
          status: "pending" | "paid" | "failed" | "refunded";
          asaas_payment_id: string | null;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["transactions"]["Row"], "created_at" | "updated_at"> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["transactions"]["Insert"]>;
      };
      tournaments: {
        Row: {
          id: string;
          name: string;
          type: "monthly" | "quarterly";
          game: string;
          status: "registration_open" | "registration_closed" | "in_progress" | "completed" | "cancelled";
          scheduled_date: string;
          max_teams: number;
          entry_fee_cents: number;
          prize_pool_cents: number;
          carry_over_cents: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["tournaments"]["Row"], "created_at" | "updated_at"> & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["tournaments"]["Insert"]>;
      };
      teams: {
        Row: {
          id: string;
          tournament_id: string;
          name: string;
          captain_id: string;
          status: "registered" | "checked_in" | "eliminated" | "finalist";
          placement: number | null;
          transaction_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["teams"]["Row"], "created_at"> & {
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["teams"]["Insert"]>;
      };
      team_members: {
        Row: {
          team_id: string;
          profile_id: string;
          joined_at: string;
        };
        Insert: {
          team_id: string;
          profile_id: string;
          joined_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["team_members"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      package_type: "hora_vale" | "hora_pico" | "pacote_3h" | "corujao";
      session_status: "active" | "completed" | "cancelled";
      transaction_type: "purchase" | "refund" | "credit_add" | "credit_use";
      payment_method: "pix" | "credit_card" | "debit_card" | "credits" | "cash";
      payment_status: "pending" | "paid" | "failed" | "refunded";
      tournament_type: "monthly" | "quarterly";
      tournament_status: "registration_open" | "registration_closed" | "in_progress" | "completed" | "cancelled";
      team_status: "registered" | "checked_in" | "eliminated" | "finalist";
      user_role: "customer" | "staff" | "admin";
    };
  };
}
