// This file is auto-generated by TanStack Router when you run `vite dev`
// Manual edits will be overwritten. Add routes in src/routes/
import { createRootRoute, createRoute, createRouter } from "@tanstack/react-router";
import { RootLayout } from "./routes/__root";
import { IndexPage } from "./routes/index";

const rootRoute = createRootRoute({ component: RootLayout });
const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: "/", component: IndexPage });

export const routeTree = rootRoute.addChildren([indexRoute]);
